package com.scm.demo.customer.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-20T19:52:27.244+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "CustomerMgr",
                  wsdlLocation = "http://localhost/Spring-CXF-Mybatis/services/customerService?wsdl",
                  targetNamespace = "http://service.ws.demo.scm.com/")
public class CustomerMgr extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.demo.scm.com/", "CustomerMgr");
    public final static QName CustomerMgrPort = new QName("http://service.ws.demo.scm.com/", "CustomerMgrPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/Spring-CXF-Mybatis/services/customerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerMgr.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost/Spring-CXF-Mybatis/services/customerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerMgr(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerMgr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerMgr() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerMgr(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerMgr(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerMgr(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerMgrPortType
     */
    @WebEndpoint(name = "CustomerMgrPort")
    public CustomerMgrPortType getCustomerMgrPort() {
        return super.getPort(CustomerMgrPort, CustomerMgrPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerMgrPortType
     */
    @WebEndpoint(name = "CustomerMgrPort")
    public CustomerMgrPortType getCustomerMgrPort(WebServiceFeature... features) {
        return super.getPort(CustomerMgrPort, CustomerMgrPortType.class, features);
    }

}
