package com.scm.demo.customer.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-20T19:52:27.214+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.ws.demo.scm.com/", name = "CustomerMgrPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerMgrPortType {

    @WebMethod
    @RequestWrapper(localName = "savePerson", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.SavePerson")
    @ResponseWrapper(localName = "savePersonResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.SavePersonResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer savePerson(
        @WebParam(name = "person", targetNamespace = "")
        com.scm.demo.customer.client.Customers person
    );

    @WebMethod
    @RequestWrapper(localName = "updatePerson", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.UpdatePerson")
    @ResponseWrapper(localName = "updatePersonResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.UpdatePersonResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer updatePerson(
        @WebParam(name = "person", targetNamespace = "")
        com.scm.demo.customer.client.Customers person
    );

    @WebMethod
    @RequestWrapper(localName = "deletePerson", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.DeletePerson")
    @ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.DeletePersonResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer deletePerson(
        @WebParam(name = "person", targetNamespace = "")
        com.scm.demo.customer.client.Customers person
    );

    @WebMethod
    @RequestWrapper(localName = "getPersonList", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.GetPersonList")
    @ResponseWrapper(localName = "getPersonListResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.customer.client.GetPersonListResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<com.scm.demo.customer.client.Customers> getPersonList(
        @WebParam(name = "person", targetNamespace = "")
        com.scm.demo.customer.client.Customers person
    );
}
