package com.scm.demo.product.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-20T19:55:07.511+08:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://service.ws.demo.scm.com/", name = "ProductMgrPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductMgrPortType {

    @WebMethod
    @RequestWrapper(localName = "deleteProduct", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.DeleteProduct")
    @ResponseWrapper(localName = "deleteProductResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.DeleteProductResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer deleteProduct(
        @WebParam(name = "product", targetNamespace = "")
        com.scm.demo.product.client.Products product
    );

    @WebMethod
    @RequestWrapper(localName = "getProductList", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.GetProductList")
    @ResponseWrapper(localName = "getProductListResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.GetProductListResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.util.List<com.scm.demo.product.client.Products> getProductList(
        @WebParam(name = "product", targetNamespace = "")
        com.scm.demo.product.client.Products product
    );

    @WebMethod
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.UpdateProductResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer updateProduct(
        @WebParam(name = "product", targetNamespace = "")
        com.scm.demo.product.client.Products product
    );

    @WebMethod
    @RequestWrapper(localName = "saveProduct", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.SaveProduct")
    @ResponseWrapper(localName = "saveProductResponse", targetNamespace = "http://service.ws.demo.scm.com/", className = "com.scm.demo.product.client.SaveProductResponse")
    @WebResult(name = "result", targetNamespace = "")
    public java.lang.Integer saveProduct(
        @WebParam(name = "product", targetNamespace = "")
        com.scm.demo.product.client.Products product
    );
}
