package com.scm.demo.product.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-20T19:55:07.543+08:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "ProductMgr",
                  wsdlLocation = "http://localhost/Spring-CXF-Mybatis/services/productService?wsdl",
                  targetNamespace = "http://service.ws.demo.scm.com/")
public class ProductMgr extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.demo.scm.com/", "ProductMgr");
    public final static QName ProductMgrPort = new QName("http://service.ws.demo.scm.com/", "ProductMgrPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost/Spring-CXF-Mybatis/services/productService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProductMgr.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost/Spring-CXF-Mybatis/services/productService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProductMgr(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProductMgr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductMgr() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProductMgr(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProductMgr(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProductMgr(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ProductMgrPortType
     */
    @WebEndpoint(name = "ProductMgrPort")
    public ProductMgrPortType getProductMgrPort() {
        return super.getPort(ProductMgrPort, ProductMgrPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductMgrPortType
     */
    @WebEndpoint(name = "ProductMgrPort")
    public ProductMgrPortType getProductMgrPort(WebServiceFeature... features) {
        return super.getPort(ProductMgrPort, ProductMgrPortType.class, features);
    }

}
